# Labels for luminai-genesis
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: infra
  color: cfd3d7
  description: Infrastructure and CI
- name: security
  color: e99695
  description: Security related issues
- name: triage
  color: 1d76db
  description: Needs triage
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: good first issue
  color: 7057ff
  description: Good for newcomers
